#!/usr/bin/env bash
set -euo pipefail

# End-to-end demo:
# 1) Codex implements + local tests
# 2) commit + push
# 3) remote pull + run pipeline
# 4) fetch artifacts back
#
# Usage:
#   bash tools/full_auto.sh --remote USER@HOST --repo-dir ~/repos/codex_outline_demo

REMOTE=""
REMOTE_REPO_DIR=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --remote) REMOTE="$2"; shift 2;;
    --repo-dir) REMOTE_REPO_DIR="$2"; shift 2;;
    *) echo "Unknown arg: $1"; exit 2;;
  esac
done

if [[ -z "$REMOTE" || -z "$REMOTE_REPO_DIR" ]]; then
  echo "Usage: bash tools/full_auto.sh --remote USER@HOST --repo-dir ~/repos/codex_outline_demo"
  exit 2
fi

bash tools/local_auto.sh

python tools/validate_outline.py
.venv/bin/python -m pytest -q

# Commit if needed
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "ERROR: run this inside a git repo."
  exit 1
fi

if [[ -n "$(git status --porcelain)" ]]; then
  git add -A
  git commit -m "Implement outline-driven pipeline (autogenerated via Codex)"
fi

# Push (requires you to set origin)
git push

# Remote run
RUN_ID="remote_$(date +%Y%m%d_%H%M%S)"
REMOTE_OUT="$REMOTE_REPO_DIR/runs/$RUN_ID"

ssh "$REMOTE" "set -euo pipefail; mkdir -p '$REMOTE_REPO_DIR'; \
  if [ ! -d '$REMOTE_REPO_DIR/.git' ]; then echo 'Remote repo missing .git; clone it first.'; exit 2; fi; \
  cd '$REMOTE_REPO_DIR'; git pull --rebase --autostash; \
  python3 -m src.pipeline --out '$REMOTE_OUT' --seed 0 --n-samples 400 --epochs 100 --lr 0.2"

# Fetch artifacts
mkdir -p runs/_fetched
scp -r "$REMOTE:$REMOTE_OUT" "runs/_fetched/$RUN_ID"

echo
echo "DONE. Remote artifacts fetched to: runs/_fetched/$RUN_ID"
